### ISSUE TITLE
Print Multiple Image 

### ISSUE THREAD

**Issue by jaumard** [mobileprint/android-print-sdk#2]
Is it possible to print multiple images?

I try this : 
```
ImageAsset imageAsset = new ImageAsset(getActivity(),
                                userPickedBitmap,
                                ImageAsset.MeasurementUnits.INCHES,
                                widthInches, heightInches);
ImageAsset imageAsset2 = new ImageAsset(getActivity(),
                                userPickedBitmap2,
                                ImageAsset.MeasurementUnits.INCHES,
                                widthInches, heightInches);

PrintItem printItem = new ImagePrintItem(imageAsset);
PrintItem printItem2 = new ImagePrintItem(imageAsset2);
PrintJobData printJobData = new PrintJobData(getActivity(), printItem);
printJobData.addPrintItem(printItem2);
 PrintUtil.setPrintJobData(printJobData);
PrintUtil.print(getActivity());
```
And get : 
```
E/AndroidRuntime: FATAL EXCEPTION: main
Process: com., PID: 28385
java.lang.RuntimeException: Unable to start activity ComponentInfo{com./com.hp.mss.hpprint.activity.PrintPreview}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2200)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250)
at android.app.ActivityThread.access$800(ActivityThread.java:139)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1200)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5105)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at com.hp.mss.hpprint.activity.PrintPreview.getSpinnerText(PrintPreview.java:159)
at com.hp.mss.hpprint.activity.PrintPreview.initializeSpinnerData(PrintPreview.java:127)
at com.hp.mss.hpprint.activity.PrintPreview.onCreate(PrintPreview.java:79)
at android.app.Activity.performCreate(Activity.java:5275)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250) 
at android.app.ActivityThread.access$800(ActivityThread.java:139) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1200) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:136) 
at android.app.ActivityThread.main(ActivityThread.java:5105) 
at java.lang.reflect.Method.invokeNative(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:515) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608) 
at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by jmcnew** [comment]
Currently, each printItem must have a unique size. The sdk is not designed to handle a list of print items. That is in the backlog for a future release.

**Comment by YNEJ** [comment]
Hello, is an update planned soon for this evolution?
